# Generated by Django 3.0.6 on 2020-06-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
