# Generated by Django 3.0.6 on 2020-06-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200602_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100000),
        ),
    ]
