# Generated by Django 3.0.6 on 2020-06-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200603_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['timestamp'], 'verbose_name': 'Articles'},
        ),
    ]
