# Generated by Django 3.0.6 on 2020-06-04 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200604_1306'),
        ('articles', '0006_articles_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
