# Generated by Django 3.0.6 on 2020-06-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200605_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Articles'},
        ),
    ]
