# Generated by Django 3.0.7 on 2020-06-10 09:47

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200609_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to=articles.models.image_path),
        ),
    ]
