# Generated by Django 3.0.7 on 2020-06-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200610_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
